/****************************************************************************
* Nombre:		sp_buscarOperador												                *
* Autor:		Pedro Ochoa																		*
* Fecha:		03/03/2022																		*
* Descripción:	Procedimiento Almacenado para buscar un operador                              *
****************************************************************************/
-----------------BUSCAR------------------------------------------------------
CREATE PROCEDURE sp_buscarOperador
AS 
BEGIN 
    SELECT*
    FROM operadores 
END